version: 3

vars:
  SOURCE_FILES: 'src/**/*.{ts,html,svelte}'

tasks:
  install:
    desc: Install project dependencies
    cmds:
      - yarn install --immutable

  format:
    desc: Format the codebase
    cmds:
      - npx prettier --plugin-search-dir . --write .

  lint:
    desc: Lint the codebase
    cmds:
      - npx prettier --plugin-search-dir . --check .
      - npx eslint .
      - npx svelte-kit sync
      - npx svelte-check --tsconfig ./tsconfig.json

  dev:
    desc: Run the development server
    cmds:
      - npx vite dev
    env:
      NODE_ENV: development

  build:
    desc: Build the application
    deps:
      - task: lint
    cmds:
      - npx vite build
    env:
      NODE_ENV: production

  test:unit:
    desc: Run unit tests
    cmds:
      - npx vitest run
    env:
      NODE_ENV: test

  test:watch:
    desc: Run unit tests in watch mode
    cmds:
      - npx vitest watch
    env:
      NODE_ENV: test

  test:e2e:
    desc: Run end-to-end tests
    deps:
      - task: build
    cmds:
      - npx playwright install
      - npx playwright test
    env:
      NODE_ENV: production

  test:
    desc: Run the full acceptance test suite
    deps:
      - task: test:unit
      - task: test:e2e
