version: 3

dotenv:
  - .env

tasks:
  install:
    desc: Install project dependencies
    cmds:
      - task: env
      - yarn install --immutable

  env:
    internal: true
    status:
      - test -f .env
    cmds:
      - cp .env.example .env

  format:
    desc: Format the codebase
    cmds:
      - npx prettier --plugin-search-dir . --write .

  lint:
    desc: Lint the codebase
    cmds:
      - npx prettier --plugin-search-dir . --check .
      - npx eslint .
      - npx svelte-kit sync
      - npx svelte-check --tsconfig ./tsconfig.json

  dev:
    desc: Run the development server
    cmds:
      - npx vite dev
    env:
      NODE_ENV: development

  build:
    desc: Build the application
    deps:
      - task: lint
    cmds:
      - npx vite build
    env:
      NODE_ENV: production

  serve:
    desc: Serve the application
    cmds:
      - npx vite preview
    env:
      NODE_ENV: production

  test:unit:
    desc: Run unit tests
    cmds:
      - npx vitest run
    env:
      NODE_ENV: test

  test:watch:
    desc: Run unit tests in watch mode
    cmds:
      - npx vitest watch --no-coverage
    env:
      NODE_ENV: test

  test:e2e:
    desc: Run end-to-end tests
    deps:
      - task: build
    cmds:
      - npx playwright install
      - npx playwright test
    env:
      NODE_ENV: production

  test:
    desc: Run the full acceptance test suite
    deps:
      - task: test:unit
      - task: test:e2e
