version: 3

vars:
  SOURCE_FILES: 'src/**/*.{ts,html,svelte}'
  TEST_FILES: 'tests/**/*.ts'

tasks:
  install:
    desc: Install project dependencies
    sources:
      - package.json
      - yarn.lock
      - .yarnrc.yml
    cmds:
      - yarn install --immutable --immutable-cache --check-cache

  format:
    desc: Format the codebase
    sources:
      - '{{.SOURCE_FILES}}'
      - '{{.TEST_FILES}}'
    cmds:
      - npx prettier --plugin-search-dir . --write .

  lint:
    desc: Lint the codebase
    sources:
      - '{{.SOURCE_FILES}}'
      - '{{.TEST_FILES}}'
    cmds:
      - npx prettier --plugin-search-dir . --check .
      - npx eslint .
      - npx svelte-kit sync
      - npx svelte-check --tsconfig ./tsconfig.json

  dev:
    desc: Run the development server
    cmds:
      - npx vite dev

  build:
    desc: Build the application
    deps:
      - task: lint
    sources:
      - '{{.SOURCE_FILES}}'
    cmds:
      - npx vite build

  test:unit:
    desc: Run unit tests
    sources:
      - '{{.SOURCE_FILES}}'
      - '{{.TEST_FILES}}'
    cmds:
      - npx vitest run

  test:e2e:
    desc: Run end-to-end tests
    sources:
      - '{{.SOURCE_FILES}}'
      - '{{.TEST_FILES}}'
    deps:
      - task: build
    cmds:
      - npx playwright test

  test:
    desc: Run the full acceptance test suite
    deps:
      - task: test:unit
      - task: test:e2e
